# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
  
  security:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Gitleaks
        uses: eeveebank/github-actions-gitleaks@v1.0.0
        with:
          depth: 1

  docker:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: startlingadama/backend-app-nodejs:v1
    
  cd_local:
    needs: docker
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      # L'ajout de la clé ssh
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CD_SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      # L'ip du server pour la reconnaissance de host
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.CD_SSH_HOST }} >> ~/.ssh/known_host
      # Deploiment de conteneurs docker
      - name: deploy containers
        run: ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.CD_SSH_HOST }} 'sudo docker run --rm -dit -p 9090:9090 startlingadama/backend-app-nodejs:v2'
      # Chargement d'un fichier par rsync
      - name: Send file over ssh
        run: rsync -avz README.md ubuntu@${{ secrets.CD_SSH_HOST }}:/home/startlingadama 
    
