name:  ci

on: 
        push:
                branches: [ main ]
        pull_request:
                branches: [ main ]

jobs:
        build:
                runs-on: ubuntu-latest

                strategy:
                        matrix:
                                node-version: [16.x]

                steps:
                        -uses: actions/checkout@v2
                        -name: Use Node.js ${{ matrix.node-version }}
                        uses: actions/setup-node@v2
                        with:
                                noe-version: ${{ matrix.node-version }}
                                cache: 'npm'
                        -run: npm ci 


        test:
                needs: build
                runs-on: ubuntu-latest

                strategy:
                        matrix:
                                node-version: [16.x]

                steps:
                        - uses: actions/checkout@v2
                        - name: Use Node.js ${{ matrix.node-version }}
                          uses: actions/setup-node@v2
                          with:
                                  node-version: ${{ matrix.node-version }}
                                  cache: 'npm'
                        - run: npm ci
                        - run: npm test
                        
       security:
               needs: test
               runs-on: ubuntu-latest

               steps:
                       - uses: actions/checkout@v2
                       - name: Run Gitleaks
                         uses: eeveebank/github-actions-gitleaks@v1.0.0
                         with:
                                 depth: 1
          
        dokcer:
                needs: test
                runs-on: ubuntu-last

                steps:
                        - name: Set up Docker Build
                          uses: docker/setup-buildx-action@v1
                        - name: Login to Dockerhub
                          uses: docker/login-action@v1
                          with:
                                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                                  password: ${{ secrets.DOCKERHUB_TOKEN }}

                        - name: Build and push
                          uses: docker/build-push-action@v2
                          with:
                                  push: true
                                  tags: startlingadama/backend-app-nodejs:v1

